const lang={
    major:{
        connectedWallet:"ربط المحفظة",
        blockChainFinance:"كتلة سلسلة المالية الحرة",
        CircularMutualAid:"دورة الألعاب المتبادلة",
        startMoney:"بداية ",
        onePointFive:"1.5%",
        everyProfit:"الدخل في دورة",
        twentyPointFive:"22.5% ",
        luckyPool:"محظوظ داخلي",
        copywriting1:"ثابت الدخل مرئية ، الأموال الواردة والصادرة يمكن التحقق منها بشفافية ، أي ثغرات",
        copywriting2:"ارتفاع العائد على الودائع",
        copywriting3:"الفائدة الأولية 15 يوما من تاريخ الانسحاب",
        copywriting4:"تشفير العملة من خلال الاستثمار في عمليات الشراء الأسبوعية أو الشهرية",
        trustPlatform:"الأكثر موثوقية منصة إيداع",
        chooseFDF:"وفيما يلي بعض الأسباب لماذا اخترت قوات الدفاع الذاتى",
        footLeft1:"لا مركزية على الإطلاق",
        footLeft2:"لا مركزية على الإطلاق <br> كل شيء يتم تنفيذه تلقائيا مع رمز العقد الذكي",
        footRight1:"عوائد عالية ومنخفضة المخاطر",
        footRight2:"يمكن الحصول على ما يصل إلى 40 ٪ من العائدات <br> ولكن ليس ودائع عالية المخاطر",
    },
    FDFIDO:{
        SnapUp:"و رمز ، صب NFT",
        ProfitSharing:"كسب أرباح",
        FTokenBalance:"و رمز الحالي الخاص بك",
        NFTTokenBalance:"NFT الحالي الخاص بك",
        PCS:"ص",
        SnapUping:"المشاركة في شراء",
        SnapUpEnd:"الاندفاع هو أكثر",
        ClaimToken:"الحصول على رمز",
        ClaimNft:"الحصول على NFT",
        threeStep:"ثلاث خطوات للحصول على مكافأة",
        inviter:"دعوة 10 أشخاص",
        tenPerson:"عشرة أشخاص سارع إلى النجاح",
        ClaimANft:"صب NFT",
        TotalInvitation:"عدد الدعوات المتاحة حاليا :"
    },
    orderDetails:{
        contractAddress:"عنوان العقد",
        platformTime:"منصة تشغيل الوقت",
        CyclicalReturn:"دورة الدخل",
        orderDetail:"تفاصيل النظام",
        orderAmount:"مبلغ الطلب",
        dataOfDeposit:"تاريخ الإيداع",
        ThawingData:"ذوبان التاريخ",
        orderStatus:"وضع النظام",
        Status:"انتهى",

    },
    sideSlide:{
        HomePage:"الصفحة الرئيسية",
        NFTpool:"NFT تجمع",
        pannel:"لوحة أجهزة القياس",
        myTeam:"فريقي",
        orderDetail:"تفاصيل النظام",
        gameRules:"قواعد اللعبة",
        whitePaper:"ورقة بيضاء",
        AuditReport:"تقرير مراجعة الحسابات",
        IDOswitch:"ايدو التبديل",
        copyInviteUrl:"نسخ دعوة الرابط", 
    },
    IN:{
        principal:"رأس المال",
        Equivalent:"معادلة",
        OneCycleReturn:"دورة الدخل", 
        PrincipalAndIncome:"رأس المال والدخل",
        copywriting1:"15 يوما في دورة واحدة ، 22.5 في المائة من الأرباح لكل دورة",
        copywriting2:"إذا كان المبلغ هو أكبر من أو يساوي المبلغ في الفترة السابقة ، يمكن سحب المبلغ مرتين و زيادة يوم واحد فترة التجميد دون زيادة الدخل ، والحد الأقصى زيادة 45 يوما لن تزيد .",
        UseIntegral:"استخدام التكامل",
        justOne:"( مرة واحدة فقط ، ذوبان الحالي لا يتجزأ : )",
        MinAmount:"من أجل الحد الأدنى 100 ش ، يرجى إدخال 100 مرات",
        ensure:"أكّد" ,
        placeholder:"من فضلك أدخل 100"
    },
    OUT:{
        UnfrozenDeposit:"ذوبان الودائع",
        layerIncome:"طبقة الدخل",
        freeze:"تجمد",
        luckyPrize:"جائزة الحظ",
        CyclicalReturn:"دورة الدخل",
        withdrawAmount:"سحب المبلغ"
    },
    SplitAccount:{
        SplitAccounts:"تقسيم الحساب",
        useIntegral:"التكامل المتاحة",
        freezeIntegral:"تجميد لا يتجزأ",
        amount:"مبلغ",
        collectionAddress:"عنوان الدفع",
        commission:"رسوم المعاملات",
        rollOut:"خروج"

    },
    IDOswitch:{
        totalNft:"شبكة كاملة NFT عدد",
        stopIDO:"توقف ايدو",
        startclaim:"قوات الدفاع الذاتى و NFT" ,
        HaveStopped:"توقف",
        closeedClaim:"إغلاق قوات الدفاع والأمن NFT"
    },
    NFTPOOL:{
        holdNFT:" عقد NFT ",
        DivideEqually:"تقاسم المكافآت", 
        currentPrizePool:"جائزة بركة",
        hour24claim:"",
        hour:"ساعة .",
        minutes:"دقيقة .",
        seconds:"ثانية .",
        currentlyAvailable:"الأرباح المستحقة حاليا",
        ImmediateClaim:"الحصول على الفور"
    },
    PANNEL:{
        playersNum:"عدد اللاعبين",
        luckyPrizePool:"محظوظ برك",
        notStarted:"لا تبدأ",
        myleveal:"بلدي الصف",
        GrossIncome:"مجموع الإيرادات",
        myInviter:"دعوتي",
        myinviterUrl:"بلدي دعوة الرابط",
        more:"أكثر .",
        copyurl:"نسخ الرابط"
    },
    MYTEAM:{
         PersonPerformance:"الأداء الفردي",
         inviteUser:"دعوة المستخدم",
         RegionalPerformance:"الأداء الإقليمي",
         CommunityPerformance:"أداء المجتمع",
         myteam:"فريقي",
         address:"عنوان",
         totalAmount:"المبلغ التراكمي",
         teamPerformance:"أداء الفريق" 
    },
    tips:{
        submitted:"قدم",
        NotOpenYet:"فتح",
        loading:"تسجيل..",
        UnregisteredInvitation:"هذا العنوان غير مسجل يرجى الاتصال مزكي للحصول على دعوة الرابط",
        inputMoney:"أدخل مبلغ الشراء",
        snapUpRatio:"الاستيلاء على نسبة",
        cancel:"ألغى",
        snapUp:"شراء على الفور",
        copy:"نسخ",
        noregister:"هذا العنوان غير مسجل يرجى الاتصال مزكي للحصول على رابط التسجيل",

    },
    dialog:{
        errorNum:"يجب أن يكون الإدخال 100 صحيح متعددة !",
        amount:"أدخل مبلغ الشراء",
        rate:"الاستيلاء على نسبة",
        cancel:"ألغى",
        buying:"التسرع في شراء",
        success:"شراء ناجحة !",
        successed:"النجاح .",
        faild:"هزم",
        rightnow:"شراء على الفور"
    }

}
export default lang