const lang={
    major:{
        connectedWallet:"Connect Wallet",
        blockChainFinance:"Blockchain ",
        CircularMutualAid:"free Finance",
        startMoney:"explore",
        onePointFive:"1.5%",
        everyProfit:"Return per period",
        twentyPointFive:"22.5% ",
        luckyPool:"Lucky pool",
        copywriting1:"Static income visible, funds in and out of transparency can be checked, no tricks",
        copywriting2:"High yield deposit",
        copywriting3:"Initial 15-day refunded interest",
        copywriting4:"Invest slowly in cryptocurrencies by scheduling weekly or monthly purchases",
        trustPlatform:"The most trusted deposit platform",
        chooseFDF:"Here are a few reasons why you might choose FDF",
        footLeft1:"Fully decentralized",
        footLeft2:"Everything is automatically executed by smart contract code",
        footRight1:"High yield and low risk",
        footRight2:"It is possible to achieve gains of up to 40% <br> But not risky deposits",
    },
    FDFIDO:{
        SnapUp:"Buy F token,Mint NFT",
        ProfitSharing:"Earn a profit share",
        FTokenBalance:"Your F tokens",
        NFTTokenBalance:"Your NFT",
        PCS:"PCS",
        SnapUping:"Snap up",
        SnapUpEnd:"The snap up is over",
        ClaimToken:"claim token",
        ClaimNft:"claim NFT",
        threeStep:"Three steps are rewarded",
        inviter:"Invite 10 people",
        tenPerson:"Ten people",
        ClaimANft:"mint NFT",
        TotalInvitation:"Current valid number of inviters:"
    },
    orderDetails:{
        contractAddress:"Contract address",
        platformTime:"Platform running time",
        CyclicalReturn:"Periodic return",
        orderDetail:"Order Details",
        orderAmount:"Amount of order",
        dataOfDeposit:"Date of deposit",
        ThawingData:"Date of thaw",
        orderStatus:"Order status",
        Status:"Completed",

    },
    sideSlide:{
        HomePage:"HOME",
        NFTpool:"NFT pool",
        pannel:"Pannel",
        myTeam:"My team",
        orderDetail:"Order Details",
        gameRules:"Rules of the Game",
        whitePaper:"White Paper",
        AuditReport:"Audit report",
        IDOswitch:"IDO switch",
        copyInviteUrl:"Copy invitation link", 
    },
    IN:{
        principal:"Funding",
        Equivalent:"Equal value",
        OneCycleReturn:"one period", 
        PrincipalAndIncome:"revenue",
        copywriting1:"The 15-day cycle yields 22% per cycle",
        copywriting2:"After the maturity of the principal of the cycle, it is necessary to continue to place an order in the next cycle, and the amount is greater than or equal to the amount placed in the previous cycle. Only then can the order be withdrawn twice. The freeze period of 1 day is increased, and the income is not increased",
        UseIntegral:"Using credits",
        justOne:" (Only once:)",
        MinAmount:"Minimum order 100U, please enter multiple of 100",
        ensure:"submit",
        placeholder:"Please enter a multiple of 100"
    },
    OUT:{
        UnfrozenDeposit:"Unfreeze deposits",
        layerIncome:"Layer revenue",
        freeze:"Freeze",
        luckyPrize:"Lucky prize",
        CyclicalReturn:"Periodic return",
        withdrawAmount:"Withdrawable amount"
    },
    SplitAccount:{
        SplitAccounts:"Split accounts",
        useIntegral:"Available credits",
        freezeIntegral:"Freezing credits",
        amount:"Amount",
        collectionAddress:"Collection address",
        commission:"Transaction fee",
        rollOut:"Turn out"

    },
    IDOswitch:{
        totalNft:"ALL NFT",
        stopIDO:"Stop IDO",
        startclaim:"Enable to receive FDF and NFT" ,
        HaveStopped:"Has been stopped",
        closeedClaim:"Turn off receiving FDF and NFT"
    },
    NFTPOOL:{
        holdNFT:"Holding NFT",
        DivideEqually:"Divide the prize pool equally", 
        currentPrizePool:"Prize pool",
        hour24claim:"Every 24 hours claim",
        hour:"h",
        minutes:"m",
        seconds:"s",
        currentlyAvailable:"Dividends are currently available",
        ImmediateClaim:"Get it now"
    },
    PANNEL:{
        playersNum:"Number of players",
        luckyPrizePool:"Lucky pool",
        notStarted:"Not started",
        myleveal:"My level",
        GrossIncome:"Total revenue",
        myInviter:"My inviter",
        myinviterUrl:"My invite link",
        more:"More",
        copyurl:"Copy links"
    },
    MYTEAM:{
         PersonPerformance:"Individual performance",
         inviteUser:"Inviting users",
         RegionalPerformance:"Regional Performance",
         CommunityPerformance:"Community performance",
         myteam:"My team",
         address:"Address",
         totalAmount:"All amount",
         teamPerformance:"Performance" 
    },
    tips:{
        submitted:"Submitted",
        NotOpenYet:"Not yet opened",
        loading:"Registering....",
        UnregisteredInvitation:"The address  not registered. Please contact the referrer for an invitation link",
        inputMoney:"Enter  amount",
        snapUpRatio:"Proportion of buying",
        cancel:"Cancel",
        snapUp:"Snap it up now",
        copy:"Copy!",
        noregister:"The address  not registered. Please contact the referrer for an invitation link",

    }

}
export default lang