const lang={
    major:{
        connectedWallet:"Conexión a la billetera",
        blockChainFinance:"Cadena de bloques de memoria",
        CircularMutualAid:"Finanzas libres",
        startMoney:"Empezar",
        onePointFive:"1,5%",
        everyProfit:"Ganancias semanales",
        twentyPointFive:"22,5% ",
        luckyPool:"Piscina de la suerte",
        copywriting1:"Los ingresos estáticos son visibles, la entrada y salida de fondos son transparentes y no hay grasa.",
        copywriting2:"Depósitos de alto rendimiento",
        copywriting3:"Intereses de la fecha de reembolso inicial de 15 días",
        copywriting4:"Invertir lentamente en criptomonedas organizando compras semanales o mensuales",
        trustPlatform:"La Plataforma de depósitos más confiable",
        chooseFDF:"Estas son algunas de las razones por las que eligió fdf.",
        footLeft1:"Descentralización completa",
        footLeft2:"Está completamente descentralizado <br> Todo se ejecuta automáticamente con el Código de contrato inteligente",
        footRight1:"Alto rendimiento y bajo riesgo",
        footRight2:"Es posible obtener hasta el 40% de las ganancias <br> Pero no depósitos de alto riesgo",
    },
    FDFIDO:{
        SnapUp:"Comprar tokens F y fundir nft",
        ProfitSharing:"Ganar ganancias",
        FTokenBalance:"Su Token F actual",
        NFTTokenBalance:"Su nft actual",
        PCS:"Uno",
        SnapUping:"Participar en la compra",
        SnapUpEnd:"La compra ha terminado",
        ClaimToken:"Recibir tokens",
        ClaimNft:"Recibir nft",
        threeStep:"Tres pasos para recompensar",
        inviter:"Invitar a 10 personas",
        tenPerson:"Diez personas triunfan",
        ClaimANft:"Recibir nft",
        TotalInvitation:"Número actual de invitaciones válidas:"
    },
    orderDetails:{
        contractAddress:"Dirección del contrato",
        platformTime:"Tiempo de funcionamiento de la plataforma",
        CyclicalReturn:"Rendimiento cíclico",
        orderDetail:"Detalles del pedido",
        orderAmount:"Importe",
        dataOfDeposit:"Depósitos",
        ThawingData:"Descongelación",
        orderStatus:"Estado",
        Status:"Completado",

    },
    sideSlide:{
        HomePage:"Página de inicio",
        NFTpool:"Grupo de premios nft",
        pannel:"Salpicadero",
        myTeam:"Mi equipo",
        orderDetail:"Detalles del pedido",
        gameRules:"Reglas del juego",
        whitePaper:"Libro Blanco",
        AuditReport:"Informe de auditoría",
        IDOswitch:"Interruptor ido",
        copyInviteUrl:"Copiar conexión de invitación", 
    },
    IN:{
        principal:"Principal",
        Equivalent:"Equivalente",
        OneCycleReturn:"Rendimiento cíclico", 
        PrincipalAndIncome:"Principal e ingresos",
        copywriting1:"Quince días es un ciclo con ganancias semanales del 22%",
        copywriting2:"Después de la expiración del principal del ciclo, es necesario continuar haciendo un pedido para el próximo ciclo, y el monto es mayor o igual al monto del pedido del ciclo anterior antes de que se pueda retirar dos veces para aumentar el período de congelación de un día, sin aumentar los ingresos, el aumento máximo de 45 días ya no aumentará.",
        UseIntegral:"Usar puntos",
        justOne:"(solo se puede una vez, puntos de deshielo actuales:)",
        MinAmount:"Haga un pedido mínimo de 100u, introduzca un múltiplo de 100",
        ensure:"Determinar" ,
        placeholder:"Por favor, introduzca un múltiplo de cien"
    },
    OUT:{
        UnfrozenDeposit:"Depósitos descongelados",
        layerIncome:"Ingresos de la capa",
        freeze:"Congelación",
        luckyPrize:"Premio de la suerte",
        CyclicalReturn:"Rendimiento cíclico",
        withdrawAmount:"Importe retirable"
    },
    SplitAccount:{
        SplitAccounts:"Cuenta dividida",
        useIntegral:"Puntos disponibles",
        freezeIntegral:"Puntos congelados",
        amount:"Importe",
        collectionAddress:"Dirección del cobro",
        commission:"Tarifas de transacción",
        rollOut:"Traslado"

    },
    IDOswitch:{
        totalNft:"Número de todas las nft",
        stopIDO:"Detener ido",
        startclaim:"Abrir para recibir FDF y nft" ,
        HaveStopped:"Se ha detenido",
        closeedClaim:"Cierre para recibir FDF y nft"
    },
    NFTPOOL:{
        holdNFT:"Mantener nft",
        DivideEqually:"Dividir por igual", 
        currentPrizePool:"Recompensa",
        hour24claim:"Recogida las 24 horas",
        days:"D",
        hour:"H",
        minutes:"M",
        seconds:"S",
        currentlyAvailable:"Actualmente se pueden recibir dividendos",
        ImmediateClaim:"Recoger de inmediato"
    },
    PANNEL:{
        playersNum:"Número de jugadores",
        luckyPrizePool:"Recompensa",
        notStarted:"Sin empezar",
        myleveal:"Mi nivel",
        GrossIncome:"Ingresos totales",
        myInviter:"Mis invitados",
        myinviterUrl:"Mi conexión de invitación",
        more:"Más",
        copyurl:"Copiar conexión"
    },
    MYTEAM:{
         PersonPerformance:"Rendimiento personal",
         inviteUser:"Invitar a los usuarios",
         RegionalPerformance:"Resultados regionales",
         CommunityPerformance:"Rendimiento de la comunidad",
         myteam:"Mi equipo",
         address:"Dirección",
         totalAmount:"Todo el Dino del pedido",
         teamPerformance:"Rendimiento del equipo" 
    },
    tips:{
        submitted:"Presentado",
        NotOpenYet:"Aún no se ha abierto",
        loading:"En el registro..",
        UnregisteredInvitation:"La Dirección no está registrada, Póngase en contacto con el recomendado para obtener una conexión de invitación.",
        inputMoney:"Introduzca el monto de la compra",
        snapUpRatio:"Proporción de compras",
        cancel:"Cancelación",
        snapUp:"Compra de inmediato",
        copy:"Copiado",
        noregister:"La Dirección no está registrada, Póngase en contacto con el recomendado para obtener la conexión registrada.",

    },
    dialog:{
        errorNum:"¡¡ la entrada debe ser un múltiplo entero de 100!",
        amount:"Introduzca el monto de la compra",
        rate:"Proporción de compras",
        cancel:"Cancelación",
        buying:"En la compra",
        success:"¡¡ la compra fue exitosa!",
        successed:"éxito",
        faild:"Fracaso",
        rightnow:"Compra de inmediato"
    }

}
export default lang