const lang = {
    major: {
        connectedWallet: "지갑 연결",
        blockChainFinance: "메모리 블록 체인 자유 금융",
        CircularMutualAid: "순환 공조 게임",
        startMoney: "돈 벌기 시작",
        onePointFive: "1.5%",
        everyProfit: "주기별 이익",
        twentyPointFive: "22.5% ",
        luckyPool: "행운의 풀",
        copywriting1: "정적 수익을 볼 수 있고, 자금 출입이 투명하고 조사할 수 있으며, 부엉이가 없다",
        copywriting2: "고수익 예금",
        copywriting3: "초기 15일 일퇴기일 이자",
        copywriting4: "매주 또는 매월 구매 일정을 통해 천천히 암호화폐에 투자합니다",
        trustPlatform: "가장 신뢰할 수 있는 예금 플랫폼",
        chooseFDF: "FDF를 선택하는 몇 가지 이유는 다음과 같습니다",
        footLeft1: "완전 탈중심화",
        footLeft2: "중앙화를 완전히 제거한 <br> 입니다. 모든 것은 스마트 계약 코드가 자동으로 실행됩니다",
        footRight1: "고수익 저위험",
        footRight2: "최대 40%의 수익을 얻을 수 있습니다 <br> 하지만 고위험 예금은 아닙니다",
    },
    FDFIDO: {
        SnapUp: "F 토큰 구매, NFT 캐스팅",
        ProfitSharing: "수익배당금 획득",
        FTokenBalance: "당신의 현재 F 토큰",
        NFTTokenBalance: "당신의 현재 NFT",
        PCS: "개",
        SnapUping: "사재기 참여",
        SnapUpEnd: "사재기 완료",
        ClaimToken: "토큰 수령",
        ClaimNft: "NFT 수령",
        threeStep: "3단계 보상",
        inviter: "10명 초대",
        tenPerson: "10명 사재기 성공",
        ClaimANft: "NFT를 캐스트할 수 있음",
        TotalInvitation: "현재 유효한 초대장 수:"
    },
    orderDetails: {
        contractAddress: "계약 주소",
        platformTime: "플랫폼 실행 시간",
        CyclicalReturn: "주기적 이익",
        orderDetail: "주문 상세 정보",
        orderAmount: "주문 금액",
        dataOfDeposit: "예금 날짜",
        ThawingData: "동결해제 날짜",
        orderStatus: "주문 상태",
        Status: "완료됨,",

    },
    sideSlide: {
        HomePage: "홈 페이지",
        NFTpool: "NFT 보너스 풀",
        pannel: "대시보드",
        myTeam: "내 팀",
        orderDetail: "주문 상세 정보",
        gameRules: "게임 규칙",
        whitePaper: "백서",
        AuditReport: "감사 보고서",
        IDOswitch: "IDO 스위치",
        copyInviteUrl: "초대 연결 복사",
    },
    IN: {
        principal: "원본",
        Equivalent: "등가",
        OneCycleReturn: "일주기 이익",
        PrincipalAndIncome: "원금 및 수익",
        copywriting1: "15일은 1주기로 주기당 22.5% 수익",
        copywriting2: "주기 원금 만기 후 다음 주기를 계속 주문해야 하며, 금액이 이전 주기 주문 금액보다 크거나 같아야 인출 2회에 1일 동결 기간을 증가시킬 수 있다. 수익을 증가시키지 않고 최대 45일 증가하면 증가하지 않는다",
        UseIntegral: "포인트 사용",
        justOne: "(한 번만 가능, 현재 해동 포인트:)",
        MinAmount: "최소 100U 주문, 100의 배수를 입력하십시오",
        ensure: "확인",
        placeholder: "100의 배수를 입력하십시오."
    },
    OUT: {
        UnfrozenDeposit: "해동 적금",
        layerIncome: "레이어 이익",
        freeze: "동결",
        luckyPrize: "행운상",
        CyclicalReturn: "주기적 이익",
        withdrawAmount: "인출 가능 금액"
    },
    SplitAccount: {
        SplitAccounts: "계정 분할",
        useIntegral: "가용 포인트",
        freezeIntegral: "포인트 동결",
        amount: "금액",
        collectionAddress: "수금 주소",
        commission: "거래수수료",
        rollOut: "내보내기"

    },
    IDOswitch: {
        totalNft: "전체 네트워크 NFT 개수:",
        stopIDO: "IDO 중지",
        startclaim: "FDF 및 NFT 수령 시작",
        HaveStopped: "정지됨",
        closeedClaim: "FDF 및 NFT 수령 닫기"
    },
    NFTPOOL: {
        holdNFT: "NFT 보유",
        DivideEqually: "상장 배당금 균등하게 나누기",
        currentPrizePool: "현재 보너스 풀",
        hour24claim: "24시간마다 청구",
        days:"일",
        hour: "시",
        minutes: "분할",
        seconds: "초",
        currentlyAvailable: "현재 배당금 수령 가능",
        ImmediateClaim: "지금 수령하세요"
    },
    PANNEL: {
        playersNum: "플레이어 수",
        luckyPrizePool: "행운의 풀",
        notStarted: "시작하지 않음",
        myleveal: "내 등급",
        GrossIncome: "총이익",
        myInviter: "내 초대인",
        myinviterUrl: "내 초대 연결",
        more: "더 많이",
        copyurl: "접속 복사"
    },
    MYTEAM: {
        PersonPerformance: "개인 실적",
        inviteUser: "사용자 초대",
        RegionalPerformance: "대구 실적",
        CommunityPerformance: "동네 실적",
        myteam: "내 팀",
        address: "주소",
        totalAmount: "계적 주문 금액",
        teamPerformance: "팀 실적"
    },
    tips: {
        submitted: "커밋됨",
        NotOpenYet: "잠시 켜지지 않음",
        loading: "로드중",
        UnregisteredInvitation: "이 주소는 등록되지 않았습니다. 추천인에게 초대 연결을 요청하십시오",
        inputMoney: "사재기 금액 입력",
        snapUpRatio: "사재기 비율",
        cancel: "취소",
        snapUp: "바로 사재기",
        copy: "복사됨",
        noregister: "이 주소는 등록되지 않았습니다. 추천인에게 등록 연결을 요청하십시오",
    },
    dialog:{
        errorNum:"100이어야 하는 정수 배수를 입력하십시오!",
        amount:"사재기 금액을 입력하다.",
        rate:"사재기 비율",
        cancel:"취소",
        buying:"사재기 중",
        success:"사재기 성공!",
        successed:"성공",
        faild:"실패",
        rightnow:"당장 사재기"
    }

}
export default lang