const lang = {
    major: {
        connectedWallet: "Подключить кошелек",
        blockChainFinance: "Блокчейн ",
        CircularMutualAid: "свободные финансы",
        startMoney: "Начинаем",
        onePointFive: "1.5%",
        everyProfit: "Еженедельный доход",
        twentyPointFive: "22,5%",
        luckyPool: "Пул удачи",
        copywriting1: "Статическая прибыль видна, доступ к средствам прозрачен и доступен, нет надоедания",
        copywriting2: "Высокодоходный депозит",
        copywriting3: "Проценты за первые 15 дней возврата",
        copywriting4: "Инвестируйте в криптовалюты медленно, организуя покупки еженедельно или ежемесячно",
        trustPlatform: "Самая надежная депозитная платформа",
        chooseFDF: "Вот несколько причин, по которым вы выбрали FDF",
        footLeft1: "Полная децентрализация",
        footLeft2: "Это полностью децентрализованный <br> Все выполняется автоматически с кодом смарт - контракта",
        footRight1: "Высокая доходность и низкий риск",
        footRight2: "Есть возможность получить до 40% прибыли <br>, но не высокорисковый депозит",
    },
    FDFIDO: {
        SnapUp: "Купить F - монеты и отлить NFT",
        ProfitSharing: "Выиграйте дивиденды",
        FTokenBalance: "Ваш текущий токен F",
        NFTTokenBalance: "Ваш текущий NFT",
        PCS: "Один",
        SnapUping: "Участие в ограблении",
        SnapUPEnd: "Покупки закончились",
        ClaimToken: "Получите токены",
        ClaimNft: "Получите NFT",
        threeStep: "Три шага, чтобы получить награду",
        inviter: "Пригласите 10 человек",
        tenPerson: "10 человек успешно ограбили",
        ClaimANft: "Можно отлить NFT",
        TotalInvitation: "Текущее число действующих приглашений:"
    },
    orderDetails: {
        contractAddress: "Адрес контракта",
        platformTime: "Время работы платформы",
        CyclicalReturn: "Поступления",
        orderDetail: "Подробности заказа",
        orderAmount: "Вклады",
        dataOfDeposit: "Дата депозита",
        ThawingData: "Оттепель",
        orderStatus: "Статус",
        Status: "Завершено",
    },
    sideSlide: {
        HomePage: "Главная страница",
        NFTpool: "Призовой пул NFT",
        pannel: "Приборная панель",
        myTeam: "Моя команда",
        orderDetail: "Подробности заказа",
        gameRules: "Правила игры",
        whitePaper: "Белая книга",
        AuditReport: "Отчет о ревизии",
        IDOswitch: "Переключатель IDO",
        copyInviteUrl: "Копировать ссылку приглашения",
    },
    IN: {
        principal: "Основная сумма",
        Equivalent: "Эквивалент",
        OneCycleReturn: "Доход за один цикл",
        PrincipalAndIncome: "Капитал и прибыль",
        copywriting1: "15 дней для цикла, еженедельная прибыль 22,5%",
        copywriting2: "По истечении срока погашения основного капитала цикла необходимо продолжить следующий цикл заказа, и сумма больше или равна сумме заказа в предыдущем цикле, прежде чем вы сможете снять заказ 2 раза, чтобы увеличить период замораживания 1 день, не увеличивая прибыль, максимальное увеличение 45 дней больше не увеличивается",
        UseIntegral: "Используйте интегралы",
        justOne: "(Можно только один раз, текущий оттаивающий интеграл:)",
        MinAmount: "Минимальный заказ 100U, введите кратное 100",
        ensure: "Определение",
        placeholder: "Введите, пожалуйста, целую сотню"
    },
    OUT: {
        UnfrozenDeposit: "Разблокирование депозитов",
        layerIncome: "Улучшение уровня",
        freeze: "Заморозить",
        luckyPrize: "Счастливый приз",
        CyclicalReturn: "Циклический доход",
        withdrawAmount: "Взимаемая сумма"
    },
    SplitAccount: {
        SplitAccounts: "Разделение счетов",
        useIntegral: "Доступность",
        freezeIntegral: "Замораживание",
        amount: "Сумма",
        collectionAddress: "Адрес получения",
        commission: "Плата за транзакции",
        rollOut: "Перевод"

    },
    IDOswitch: {
        totalNft:  "Количество NFT для всей сети",
        stopIDO: "Остановить IDO",
        startclaim: "Открыть получение FDF и NFT",
        HaveStopped: "Остановился",
        closeedClaim:  "Закрыть доступ к FDF и NFT"
    },
    NFTPOOL: {
        holdNFT: "Сейчас можно получать дивиденды.",
        DivideEqually: "Распределение дивидендов в пулах призов",
        currentPrizePool: "Призовой пул",
        hour24claim: "Получить 24 часа ",
        days:"D",
        hour: "H",
        minutes: "M",
        seconds: "S",
        currentlyAvailable: "В настоящее время можно получить дивиденды",
        ImmediateClaim: "Получить немедленно"
    },
    PANNEL: {
        playersNum: "Количество игроков",
        luckyPrizePool: "Счастливый пул",
        notStarted: "Не началось",
        myleveal: "Мой ранг",
        GrossIncome: "Общая прибыль",
        myInviter: "Мой приглашенный",
        myinviterUrl: "Мои приглашения по ссылке",
        more: "Больше",
        copyurl: " Копирование "
    },
    MYTEAM: {
        PersonPerformance: "Персонал",
        inviteUser: "Приглашение пользователей",
        RegionalPerformance: "Региональные показатели",
        CommunityPerformance: "Эффективность сообщества",
        myteam: "Моя команда",
        address: "Адрес",
        totalAmount: "Накопленная сумма заказа",
        teamPerformance: "Результаты команды"
    },
    tips: {
        submitted: "Представлено",
        NotOpenYet: "Пока не открыт",
        loading: "В процессе загрузки",
        UnregisteredInvitation: "Адрес не зарегистрирован Пожалуйста, свяжитесь с рекомендателем, чтобы получить ссылку на приглашение",
        inputMoney: "Введите сумму покупки",
        snapUpRatio: "Доля покупок",
        cancel: "Отменить",
        snapUp: "Покупайте прямо сейчас",
        copy: "Копировано",
        noregister: "Адрес не зарегистрирован Пожалуйста, свяжитесь с рекомендателем, чтобы получить ссылку на приглашение",

    },
    dialog:{
        errorNum:"Введите целое кратное 100!",
        amount:"Введите сумму покупки",
        rate:"Доля покупок",
        cancel:"Отменить",
        buying:"В процессе покупки",
        success:"Покупаю.!",
        successed:"Успех",
        faild:"Неудача",
        rightnow:"Покупка"
    },
    errormessage:{
        chainid:"Сетевые ошибки Пожалуйста, выберите сеть Polygon",
        errortitle:"Сетевая ошибка",
        walleterror:"Пожалуйста, подключите кошелек",
        wallettitle:"Ошибка",
        allerror:"Проверьте кошелек или подключение к сети"
    },
    orederState:{
        completed:"Завершено",
        associated:"Будут связаны",
        NotYetDue:"Срок не истек"
    }

}
export default lang